version: '3.7'

services:

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres_tg_bot_spp
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - /opt/tg_bot_spp/db/pgdata:/var/lib/postgresql/data
    networks:
      - tg_bot_spp

networks:
  tg_bot_spp:
    driver: bridge
