version: '3.7'

services:

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres_tgbot_icetrade
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - /opt/tgbot_icetrade/db/pgdata:/var/lib/postgresql/data
    networks:
      - tgbot_icetrade

networks:
  tgbot_icetrade:
    driver: bridge
