"""Add link text field to auction

Revision ID: baf15a1d38f5
Revises: eaf1db268c44
Create Date: 2023-10-02 12:39:30.526569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf15a1d38f5'
down_revision: Union[str, None] = 'eaf1db268c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'link')
    # ### end Alembic commands ###
