"""Add tracking bool field to auction

Revision ID: eaf1db268c44
Revises: f573ab1c1b44
Create Date: 2023-10-02 11:43:44.796159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf1db268c44'
down_revision: Union[str, None] = 'f573ab1c1b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('tracking', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'tracking')
    # ### end Alembic commands ###
